/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { XPReward } from "./XPReward";
export * as factories from "./factories";
export { XPReward__factory } from "./factories/XPReward__factory";
