/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../../common";
import type {
  ExecutorOptions,
  ExecutorOptionsInterface,
} from "../../../../../../@layerzerolabs/lz-evm-protocol-v2/contracts/messagelib/libs/ExecutorOptions";

const _abi = [
  {
    inputs: [],
    name: "Executor_InvalidLzComposeOption",
    type: "error",
  },
  {
    inputs: [],
    name: "Executor_InvalidLzReceiveOption",
    type: "error",
  },
  {
    inputs: [],
    name: "Executor_InvalidNativeDropOption",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220de6db7d5b55bb8ccbd9b2a85e19af795f34883dec0e9fd1eadf37895214fe1eb64736f6c63430008180033";

type ExecutorOptionsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ExecutorOptionsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ExecutorOptions__factory extends ContractFactory {
  constructor(...args: ExecutorOptionsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      ExecutorOptions & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): ExecutorOptions__factory {
    return super.connect(runner) as ExecutorOptions__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ExecutorOptionsInterface {
    return new Interface(_abi) as ExecutorOptionsInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ExecutorOptions {
    return new Contract(address, _abi, runner) as unknown as ExecutorOptions;
  }
}
